config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: redirect('/general')
  mount Ckeditor::Engine => '/ckeditor'

  resources :categories, only: [:show]
  resources :pages, only: [:show]
  resources :products, only: [:show]

  namespace :admin do
    resources :types, except: [:show]
    resources :menus, except: [:show]
    resources :pages # /admin/pages
    resources :categories
    resources :products
    get 'settings', to: 'settings#index'
    put 'settings', to: 'settings#update'
  end

  Page.where("slug <> ''").all.each do |page|
     get "/#{page.slug}", controller: "pages", action: "show", id: page.id
  end

end

app/models/cart.rb
class Cart
  attr_reader :items

  def self.build_from_hash hash
    items = hash["cart"]["items"].map do |item_data|
      CartItem.new item_data["product_id"], item_data["quantity"]
    end
    
    new items
  end
  
  def initialize items = []
    @items = items
  end

  def add_item product_id
    item = @items.find { |item| item.product_id == product_id }
    if item
      item.increment
    else
      @items << CartItem.new(product_id)
    end
  end

  def empty?
    @items.empty?
  end

  def serialize
    items = @items.map do |item|
      { 
        "product_id" => item.product_id,
        "quantity" => item.quantity
      }
    end

    {
      "cart" => {
        "items" => items
      }
    }
  end
end

app/models/cart_item.rb
class CartItem
  attr_reader :product_id, :quantity

  def initialize product_id, quantity = 1
    @product_id = product_id
    @quantity = quantity
  end

  def increment
    @quantity = @quantity + 1
  end

  def product
    Product.find product_id
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :pages
end

app/models/field.rb
class Field < ActiveRecord::Base
  belongs_to :page
  belongs_to :field_definition
end

app/models/field_definition.rb
class FieldDefinition < ActiveRecord::Base
  belongs_to :type
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  validates_presence_of :name
  has_many :menu_items

  accepts_nested_attributes_for :menu_items, reject_if: :all_blank
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :menu
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :category
  belongs_to :type

  has_many :fields

  accepts_nested_attributes_for :fields, reject_if: :all_blank

  # page.url
  #binding.pry
  def method_missing name, *args, &block
    field = self.fields.find { |field| field.field_definition.key == name.to_s }
    if field
      field.value
    else
      super
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
	mount_uploader :image, ImageUploader

	validates_presence_of :name, :price
	validates_numericality_of :price
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_many :field_definitions

	accepts_nested_attributes_for :field_definitions, reject_if: :all_blank
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        Rails.application.reload_routes!
        format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        Rails.application.reload_routes!
        format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :image)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_filter :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ContentController
  def show
    @category = Category.includes(:pages).find params[:id]

    render template: "category"
  end

  protected

  def template_to_render
    	if template_exists?("category-#{@category.id}")
    		"category-#{@category.id}"
    	else
    		"category"
    	end
    end
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
	before_filter :set_theme
	before_filter :retrieve_menus

	def set_theme
		theme = Setting.find_by_key('theme').value
		prepend_view_path "app/themes/#{theme}"
		self.class.layout "../../themes/#{theme}/layout"
	end

	def retrieve_menus
		@menu = Menu.all
	end
end

app/controllers/pages_controller.rb
class PagesController < ContentController
  def show
    @page = Page.find params[:id]

    render template: template_to_render
  end

  protected



  def template_to_render
    #binding pry
    if template_exists?("page-#{@page.id}")
      "page-#{@page.id}"
    elsif template_exists? "page-#{@page.type.name}"
      "page-#{@page.type.name}"
    else
      "page"
    end
  end

  # def template_to_render
  #   if template_exists?("page-#{@page.id}")
  #     "page-#{@page.id}"
  #   elsif template_exists? "page-#{@page.type.name}"
  #     "page-#{@page.type.name}"
  #   else
  #     "page"
  #   end
  # end
end

app/controllers/products_controller.rb
class ProductsController < ContentController
  def show
    @product = Product.find(params[:id])
#    respond_with @product
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def url_for_page page
		root_path + if page.slug.present?
			page.slug
		else
			"pages/#{page.id}"
		end
	end

	def url_for_menu_item menu_item
		if menu_item.url.match /:\/\// #Http://, ftp://, ect..
			menu_item.url
		else
			root_path + menu_item.url
		end
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
	def print_multiline(field)
  		field.gsub("\r\n","\n").html_safe
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/types_helper.rb
module TypesHelper
	def print_multiline(field)
  		field.gsub("\r\n","\n").html_safe
	end
end

app/views/admin/products/_form.html.haml
= form_for [ "admin", @product ], multipart: true do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  %p
    = f.label :name
    = f.text_field :name, class: "form-control"
  %p
    = f.label :price
    = f.text_field :price, class: "form-control"
  %p
    = f.label :image
    = f.file_field :image, class: "form-control"
  %p
    = f.submit 'Save', class: "btn btn-default"

app/views/admin/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', admin_product_path(@product)
\|
= link_to 'Back', admin_products_path

app/views/admin/products/index.html.haml
%h1 Listing products

%table.table.table-hover
  %thead
    %tr
      %th Name
      %th Price
      %th Image
      %th
      %th

  %tbody
    - @products.each do |product|
      %tr
        %td= link_to product.name, edit_admin_product_path(product)
        %td= number_to_currency product.price
        %td= image_tag product.image.thumb
        %td= link_to 'Show', admin_product_path(product)
        %td= link_to 'Destroy', admin_product_path(product), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Product', new_admin_product_path, class: "btn btn-primary"

app/views/admin/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', admin_products_path

app/views/admin/products/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @product.name
%p
  %b Price:
  = @product.price
%p
  %b Image:
  = @product.image

= link_to 'Edit', edit_admin_product_path(@product)
\|
= link_to 'Back', admin_products_path

app/views/products/show.html.haml
%h1= @product.name

%p Price: 
= number_to_currency @product.price
%p Image:
= image_tag @product.image, width: 300

%br
= link_to 'Edit', edit_admin_product_path(@product)
\|
= link_to 'Back', admin_products_path